Software/PromoterSoftware/PromoterSoftware/Models/Entities/Store.cs
 

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Globalization;
    using System.Linq;

    public class Store : BaseEntity
    {
        public Store()
        {
            ProjectDetails=new List<ProjectDetail>();
        }
        [Display(Name = "عنوان فروشگاه")]
        [Required(ErrorMessage = "لطفا {0} را وارد نمایید.")]
        public string Title { get; set; }
         
        [Display(Name = "شهر")]
        public Guid? CityId { get; set; }
      
        public virtual City City { get; set; }

        public virtual ICollection<ProjectDetail> ProjectDetails { get; set; }
    }
}

Software/PromoterSoftware/PromoterSoftware/Controllers/StoresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Models;

namespace PromoterSoftware.Controllers
{
    public class StoresController : Infrastructure.BaseController
    {
        private DatabaseContext db = new DatabaseContext();

        // GET: Stores
        public ActionResult Index()
        {
            var stores = db.Stores.Include(s => s.City).Where(s=>s.IsDeleted==false).OrderByDescending(s=>s.CreationDate);
            return View(stores.ToList());
        }

     
        public ActionResult Create()
        {
            ViewBag.CityId = new SelectList(db.Cities.OrderBy(c => c.Title), "Id", "Title");
            return View();
        }

        // POST: Stores/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,CityId,IsActive,CreationDate,LastModifiedDate,IsDeleted,DeletionDate,Description")] Store store)
        {
            if (ModelState.IsValid)
            {
				store.IsDeleted=false;
				store.CreationDate= DateTime.Now; 
                store.Id = Guid.NewGuid();
                db.Stores.Add(store);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CityId = new SelectList(db.Cities.OrderBy(c=>c.Title), "Id", "Title", store.CityId);
            return View(store);
        }

        // GET: Stores/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Store store = db.Stores.Find(id);
            if (store == null)
            {
                return HttpNotFound();
            }
            ViewBag.CityId = new SelectList(db.Cities.OrderBy(c => c.Title), "Id", "Title", store.CityId);
            return View(store);
        }

        // POST: Stores/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,CityId,IsActive,CreationDate,LastModifiedDate,IsDeleted,DeletionDate,Description")] Store store)
        {
            if (ModelState.IsValid)
            {
				store.IsDeleted=false;
                db.Entry(store).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CityId = new SelectList(db.Cities.OrderBy(c => c.Title), "Id", "Title", store.CityId);
            return View(store);
        }

        // GET: Stores/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Store store = db.Stores.Find(id);
            if (store == null)
            {
                return HttpNotFound();
            }
            return View(store);
        }

        // POST: Stores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Store store = db.Stores.Find(id);
			store.IsDeleted=true;
			store.DeletionDate=DateTime.Now;
 
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Software/PromoterSoftware/PromoterSoftware/Views/Stores/Create.cshtml
@model Models.Store

@{
    ViewBag.Title = "افزودن فروشگاه" ;
}

<div class="col-md-4">
    <div class="main-card mb-3 card">
        @ViewBag.description
    </div>
</div>
                        
<div class="col-md-8">
<div class="main-card mb-3 card">
<div class="card-body">

@using (Html.BeginForm("Create", "Stores",FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    

    <div class="position-relative form-group">
            @Html.LabelFor(model => model.Title)
            
                       <input name="Title" id="Title" placeholder= "@Html.DisplayNameFor(m=>m.Title)" type="text" class="form-control">
                @Html.ValidationMessageFor(model => model.Title)
        </div>
    <div class="position-relative form-group">
            @Html.LabelFor(model => model.CityId)
            
                @Html.DropDownList("CityId",null, String.Empty,new{ @class= "form-control" })
                @Html.ValidationMessageFor(model => model.CityId)
        </div>
			<div class="position-relative form-check">
			 <label class="form-check-label">
			     @Html.CheckBoxFor(model => model.IsActive)
			 @Html.DisplayNameFor(m => m.IsActive)
			 </label>
            
                       </div>
    <div class="position-relative form-group">
            @Html.LabelFor(model => model.Description)
            
                   <textarea name="Description" id="Description" placeholder= "@Html.DisplayNameFor(m=>m.Description)" class="form-control"></textarea>

                @Html.ValidationMessageFor(model => model.Description)
        </div>



       <div class="button-box">
                <input type="submit" value="ایجاد" class="btn btn-primary" />
				@Html.ActionLink("بازگشت به فهرست", "Index")
           
        </div>
   
}
        </div>
        </div>
        </div>

Software/PromoterSoftware/PromoterSoftware/Views/Stores/Delete.cshtml
@model Models.Store

@{
    ViewBag.Title = "حذف " + Server.HtmlDecode(Html.DisplayNameFor(model => model).ToString());
}

<h2>@ViewBag.Title</h2>

<h3>آیا از حذف این مورد اطمینان دارید؟</h3>
<div>    
    <hr />
    <div class="form-horizontal">        
    
         <div class="form-group">
            @Html.LabelFor(model => model.City.Title, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.City.Title)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Title)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.IsActive, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.IsActive)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.CreationDate, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.CreationDate)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.LastModifiedDate, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.LastModifiedDate)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Description)
      </div></div>

  </div>  

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

       <div class="form-group" id="buttons">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="تایید حذف" class="btn btn-primary" />
				@Html.ActionLink("بازگشت به فهرست", "Index")
            </div>
        </div>
    }
</div>

Software/PromoterSoftware/PromoterSoftware/Views/Stores/Edit.cshtml
@model Models.Store

@{
    ViewBag.Title = "ویرایش فروشگاه" ;
}


<div class="col-md-4">
    <div class="main-card mb-3 card">
        @ViewBag.description
    </div>
</div>
                        
<div class="col-md-8">
<div class="main-card mb-3 card">
<div class="card-body">


@using (Html.BeginForm("Edit", "Stores",FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
        @Html.HiddenFor(model => model.Id)

         <div class="position-relative form-group">
            @Html.LabelFor(model => model.Title)
                                     <input name="Title" id="Title" placeholder= "@Html.DisplayNameFor(m=>m.Title)" type="text" class="form-control" value="@Model.Title">
                @Html.ValidationMessageFor(model => model.Title)
            </div>
       

         <div class="position-relative form-group">
            @Html.LabelFor(model => model.CityId)
                @Html.DropDownList("CityId",null, String.Empty,new{ @class= "form-control" })
                @Html.ValidationMessageFor(model => model.CityId)
            </div>
       

        	<div class="position-relative form-check">
			 <label class="form-check-label">
			     @Html.CheckBoxFor(model => model.IsActive)
			 @Html.DisplayNameFor(m => m.IsActive)
			 </label>    
                                             @Html.ValidationMessageFor(model => model.IsActive)
            </div>
       

	 @Html.HiddenFor(model => model.CreationDate)
         <div class="position-relative form-group">
            @Html.LabelFor(model => model.Description)
                                 <textarea name="Description" id="Description" placeholder= "@Html.DisplayNameFor(m=>m.Description)" class="form-control"></textarea>
                @Html.ValidationMessageFor(model => model.Description)
            </div>
       

   <div class="button-box">
                <input type="submit" value="ثبت" class="btn btn-primary" />
				@Html.ActionLink("بازگشت به فهرست", "Index")
           
        </div>
        
  
}
        </div>
        </div>
        </div>

Software/PromoterSoftware/PromoterSoftware/Views/Stores/Index.cshtml
@model IEnumerable<Models.Store>

@{
ViewBag.Title = "فهرست فروشگاه ها" ;
    
}
@section styles{
@Html.Partial("BackEndLayout/_KendoResourcesPartial")
}
<div class="col-md-12">
    <div class="main-card mb-3 card">
        <div class="card-body">

        @(Html.Kendo().Grid(Model)
              .Name("Grid")
              .Columns(columns =>
                  {
                        columns.Bound(model => model.City.Title);
        columns.Bound(model => model.Title);
        columns.Bound(model => model.IsActive);
        columns.Bound(model => model.CreationDate);
					columns.Bound(item => @item.Id).Title("دستورات").Filterable(false).Groupable(false)
							.Template(@<text>
								          @Html.ActionLink("ویرایش", "Edit", new {id = @item.Id}, new {@class = "mb-2 mr-2 btn btn-primary" })
								          @Html.ActionLink("حذف", "Delete", new {id = @item.Id}, new {@class = "mb-2 mr-2 btn btn-warning" })
									</text>).Width(200);  
		})
		.ToolBar(toolbar =>
					{				
						toolbar.Custom().Action("Create","Stores").Text("افزودن");                          
					}
		) .Filterable().Sortable().Groupable()        
		.DataSource(dataSource => dataSource
									.Server()
					 
									.Model(model => model.Id(item => item.Id))
					)              
	)

</div>
</div>
</div>