Software/PromoterSoftware/PromoterSoftware/Models/Entities/DailyPromoterPlanAttachment.cs
 

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Globalization;
    using System.Linq;

    public class DailyPromoterPlanAttachment : BaseEntity
    { 
        [Display(Name="ضمیمه")]
        public string FileUrl { get; set; }

        public Guid DailyPromoterPlanId { get; set; }
        public virtual DailyPromoterPlan DailyPromoterPlan { get; set; }
    }
}

Software/PromoterSoftware/PromoterSoftware/Controllers/DailyPromoterPlanAttachmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Models;

namespace PromoterSoftware.Controllers
{
    public class DailyPromoterPlanAttachmentsController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        // GET: DailyPromoterPlanAttachments
        public ActionResult Index()
        {
            var dailyPromoterPlanAttachments = db.DailyPromoterPlanAttachments.Include(d => d.DailyPromoterPlan).Where(d=>d.IsDeleted==false).OrderByDescending(d=>d.CreationDate);
            return View(dailyPromoterPlanAttachments.ToList());
        }

        // GET: DailyPromoterPlanAttachments/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DailyPromoterPlanAttachment dailyPromoterPlanAttachment = db.DailyPromoterPlanAttachments.Find(id);
            if (dailyPromoterPlanAttachment == null)
            {
                return HttpNotFound();
            }
            return View(dailyPromoterPlanAttachment);
        }

        // GET: DailyPromoterPlanAttachments/Create
        public ActionResult Create()
        {
            ViewBag.DailyPromoterPlanId = new SelectList(db.DailyPromoterPlans, "Id", "Description");
            return View();
        }

        // POST: DailyPromoterPlanAttachments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FileUrl,DailyPromoterPlanId,IsActive,CreationDate,LastModifiedDate,IsDeleted,DeletionDate,Description")] DailyPromoterPlanAttachment dailyPromoterPlanAttachment)
        {
            if (ModelState.IsValid)
            {
				dailyPromoterPlanAttachment.IsDeleted=false;
				dailyPromoterPlanAttachment.CreationDate= DateTime.Now; 
                dailyPromoterPlanAttachment.Id = Guid.NewGuid();
                db.DailyPromoterPlanAttachments.Add(dailyPromoterPlanAttachment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DailyPromoterPlanId = new SelectList(db.DailyPromoterPlans, "Id", "Description", dailyPromoterPlanAttachment.DailyPromoterPlanId);
            return View(dailyPromoterPlanAttachment);
        }

        // GET: DailyPromoterPlanAttachments/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DailyPromoterPlanAttachment dailyPromoterPlanAttachment = db.DailyPromoterPlanAttachments.Find(id);
            if (dailyPromoterPlanAttachment == null)
            {
                return HttpNotFound();
            }
            ViewBag.DailyPromoterPlanId = new SelectList(db.DailyPromoterPlans, "Id", "Description", dailyPromoterPlanAttachment.DailyPromoterPlanId);
            return View(dailyPromoterPlanAttachment);
        }

        // POST: DailyPromoterPlanAttachments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FileUrl,DailyPromoterPlanId,IsActive,CreationDate,LastModifiedDate,IsDeleted,DeletionDate,Description")] DailyPromoterPlanAttachment dailyPromoterPlanAttachment)
        {
            if (ModelState.IsValid)
            {
				dailyPromoterPlanAttachment.IsDeleted=false;
                db.Entry(dailyPromoterPlanAttachment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DailyPromoterPlanId = new SelectList(db.DailyPromoterPlans, "Id", "Description", dailyPromoterPlanAttachment.DailyPromoterPlanId);
            return View(dailyPromoterPlanAttachment);
        }

        // GET: DailyPromoterPlanAttachments/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DailyPromoterPlanAttachment dailyPromoterPlanAttachment = db.DailyPromoterPlanAttachments.Find(id);
            if (dailyPromoterPlanAttachment == null)
            {
                return HttpNotFound();
            }
            return View(dailyPromoterPlanAttachment);
        }

        // POST: DailyPromoterPlanAttachments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            DailyPromoterPlanAttachment dailyPromoterPlanAttachment = db.DailyPromoterPlanAttachments.Find(id);
			dailyPromoterPlanAttachment.IsDeleted=true;
			dailyPromoterPlanAttachment.DeletionDate=DateTime.Now;
 
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DeleteByPromoter(Guid id)
        {
            DailyPromoterPlanAttachment dailyPromoterPlanAttachment = db.DailyPromoterPlanAttachments.Find(id);
			dailyPromoterPlanAttachment.IsDeleted=true;
			dailyPromoterPlanAttachment.DeletionDate=DateTime.Now;
 
            db.SaveChanges();
            return RedirectToAction("PromoterDailyPlanAction","DailyPromoterPlans");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Software/PromoterSoftware/PromoterSoftware/Views/DailyPromoterPlanAttachments/Create.cshtml
@model Models.DailyPromoterPlanAttachment

@{
    ViewBag.Title = "افزودن " + Server.HtmlDecode(Html.DisplayNameFor(model => model).ToString());
}

<div class="col-md-4">
    <div class="main-card mb-3 card">
        @ViewBag.description
    </div>
</div>
                        
<div class="col-md-8">
<div class="main-card mb-3 card">
<div class="card-body">

@using (Html.BeginForm("Create", "DailyPromoterPlanAttachments",FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    

    <div class="position-relative form-group">
            @Html.LabelFor(model => model.FileUrl)
            
                       <input name="FileUrl" id="FileUrl" placeholder= "@Html.DisplayNameFor(m=>m.FileUrl)" type="text" class="form-control">
                @Html.ValidationMessageFor(model => model.FileUrl)
        </div>
    <div class="position-relative form-group">
            @Html.LabelFor(model => model.DailyPromoterPlanId)
            
                @Html.DropDownList("DailyPromoterPlanId",null, String.Empty,new{ @class= "form-control" })
                @Html.ValidationMessageFor(model => model.DailyPromoterPlanId)
        </div>
			<div class="position-relative form-check">
			 <label class="form-check-label">
			     @Html.CheckBoxFor(model => model.IsActive)
			 @Html.DisplayNameFor(m => m.IsActive)
			 </label>
            
                       </div>
    <div class="position-relative form-group">
            @Html.LabelFor(model => model.Description)
            
                   <textarea name="Description" id="Description" placeholder= "@Html.DisplayNameFor(m=>m.Description)" class="form-control"></textarea>

                @Html.ValidationMessageFor(model => model.Description)
        </div>



       <div class="button-box">
                <input type="submit" value="ایجاد" class="btn btn-primary" />
				@Html.ActionLink("بازگشت به فهرست", "Index")
           
        </div>
   
}
        </div>
        </div>
        </div>

Software/PromoterSoftware/PromoterSoftware/Views/DailyPromoterPlanAttachments/Delete.cshtml
@model Models.DailyPromoterPlanAttachment

@{
    ViewBag.Title = "حذف " + Server.HtmlDecode(Html.DisplayNameFor(model => model).ToString());
}

<h2>@ViewBag.Title</h2>

<h3>آیا از حذف این مورد اطمینان دارید؟</h3>
<div>    
    <hr />
    <div class="form-horizontal">        
    
         <div class="form-group">
            @Html.LabelFor(model => model.DailyPromoterPlan.Description, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.DailyPromoterPlan.Description)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.FileUrl, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.FileUrl)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.IsActive, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.IsActive)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.CreationDate, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.CreationDate)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.LastModifiedDate, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.LastModifiedDate)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Description)
      </div></div>

  </div>  

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

       <div class="form-group" id="buttons">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="تایید حذف" class="btn btn-primary" />
				@Html.ActionLink("بازگشت به فهرست", "Index")
            </div>
        </div>
    }
</div>

Software/PromoterSoftware/PromoterSoftware/Views/DailyPromoterPlanAttachments/Details.cshtml
@model Models.DailyPromoterPlanAttachment

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>DailyPromoterPlanAttachment</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DailyPromoterPlan.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DailyPromoterPlan.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastModifiedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeletionDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeletionDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Software/PromoterSoftware/PromoterSoftware/Views/DailyPromoterPlanAttachments/Edit.cshtml
@model Models.DailyPromoterPlanAttachment

@{
    ViewBag.Title = "ویرایش " + Server.HtmlDecode(Html.DisplayNameFor(model => model).ToString());
}


<div class="col-md-4">
    <div class="main-card mb-3 card">
        @ViewBag.description
    </div>
</div>
                        
<div class="col-md-8">
<div class="main-card mb-3 card">
<div class="card-body">


@using (Html.BeginForm("Edit", "DailyPromoterPlanAttachments",FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
        @Html.HiddenFor(model => model.Id)

         <div class="position-relative form-group">
            @Html.LabelFor(model => model.FileUrl)
                                     <input name="FileUrl" id="FileUrl" placeholder= "@Html.DisplayNameFor(m=>m.FileUrl)" type="text" class="form-control" value="@Model.FileUrl">
                @Html.ValidationMessageFor(model => model.FileUrl)
            </div>
       

         <div class="position-relative form-group">
            @Html.LabelFor(model => model.DailyPromoterPlanId)
                @Html.DropDownList("DailyPromoterPlanId",null, String.Empty,new{ @class= "form-control" })
                @Html.ValidationMessageFor(model => model.DailyPromoterPlanId)
            </div>
       

        	<div class="position-relative form-check">
			 <label class="form-check-label">
			     @Html.CheckBoxFor(model => model.IsActive)
			 @Html.DisplayNameFor(m => m.IsActive)
			 </label>    
                                             @Html.ValidationMessageFor(model => model.IsActive)
            </div>
       

	 @Html.HiddenFor(model => model.CreationDate)
         <div class="position-relative form-group">
            @Html.LabelFor(model => model.Description)
                                 <textarea name="Description" id="Description" placeholder= "@Html.DisplayNameFor(m=>m.Description)" class="form-control"></textarea>
                @Html.ValidationMessageFor(model => model.Description)
            </div>
       

   <div class="button-box">
                <input type="submit" value="ثبت" class="btn btn-primary" />
				@Html.ActionLink("بازگشت به فهرست", "Index")
           
        </div>
        
  
}
        </div>
        </div>
        </div>

Software/PromoterSoftware/PromoterSoftware/Views/DailyPromoterPlanAttachments/Index.cshtml
@model IEnumerable<Models.DailyPromoterPlanAttachment>

@{
ViewBag.Title = "فهرست " + Server.HtmlDecode(Html.DisplyModelPluralName(model => model).ToString());
    
}
@section styles{
@Html.Partial("BackEndLayout/_KendoResourcesPartial")
}
<div class="col-md-12">
    <div class="main-card mb-3 card">
        <div class="card-body">

        @(Html.Kendo().Grid(Model)
              .Name("Grid")
              .Columns(columns =>
                  {
                        columns.Bound(model => model.DailyPromoterPlan.Description);
        columns.Bound(model => model.FileUrl);
        columns.Bound(model => model.IsActive);
        columns.Bound(model => model.CreationDate);
        columns.Bound(model => model.LastModifiedDate);
        columns.Bound(model => model.Description);
					columns.Bound(item => @item.Id).Title("دستورات").Filterable(false).Groupable(false)
							.Template(@<text>
									@Html.ActionLink("ویرایش", "Edit", new {id = @item.Id}, new {@class = "k-button"})
									@Html.ActionLink("حذف", "Delete", new {id = @item.Id}, new {@class = "k-button"})
									</text>).Width(200);  
		})
		.ToolBar(toolbar =>
					{				
						toolbar.Custom().Action("Create","DailyPromoterPlanAttachments").Text("افزودن");                          
					}
		)         
		.DataSource(dataSource => dataSource
									.Server()
							
									.Model(model => model.Id(item => item.Id))
					)              
	)

</div>
</div>
</div>