Software/PromoterSoftware/PromoterSoftware/Models/Entities/Project.cs
using System.Web.Mvc;

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Globalization;
    using System.Linq;

    public class Project : BaseEntity
    {
        public Project()
        {
            ProjectDetails=new List<ProjectDetail>();
            ProjectAttachments = new List<ProjectAttachment>();
            ProjectProducts = new List<ProjectProduct>();
        }

        [Display(Name = "عنوان پروژه")]
        public string Title { get; set; }

        [Display(Name = "تاریخ شروع")]
        [UIHint("PersianDatePicker")]
        public DateTime StartDate { get; set; }

        [Display(Name = "تاریخ پایان")]
        [UIHint("PersianDatePicker")]
        public DateTime? EndDate { get; set; }

        [Display(Name = "مشتری")]
        public Guid CustomerId { get; set; }
        public virtual Customer Customer { get; set; }

        [AllowHtml]
        [Display(Name = "توضیحات")]
        [DataType(DataType.MultilineText)]
        public string Body { get; set; }

        public virtual ICollection<ProjectDetail> ProjectDetails { get; set; }
        public virtual ICollection<ProjectAttachment> ProjectAttachments { get; set; }
        public virtual ICollection<ProjectProduct> ProjectProducts { get; set; }



        #region NotMapped

        [Display(Name = "تاریخ شروع")]
        [NotMapped]
        public string StartDateStr
        {
            get
            {
                System.Globalization.PersianCalendar pc = new System.Globalization.PersianCalendar();
                string year = pc.GetYear(StartDate).ToString().PadLeft(4, '0');
                string month = pc.GetMonth(StartDate).ToString().PadLeft(2, '0');
                string day = pc.GetDayOfMonth(StartDate).ToString().PadLeft(2, '0');
                return String.Format("{0}/{1}/{2}", year, month, day );
            }
        }

        [Display(Name = "تاریخ پایان")]
        [NotMapped]
        public string EndDateStr
        {
            get
            {
                if (EndDate == null)
                    return string.Empty;

                System.Globalization.PersianCalendar pc = new System.Globalization.PersianCalendar();
                string year = pc.GetYear(EndDate.Value).ToString().PadLeft(4, '0');
                string month = pc.GetMonth(EndDate.Value).ToString().PadLeft(2, '0');
                string day = pc.GetDayOfMonth(EndDate.Value).ToString().PadLeft(2, '0');
                return String.Format("{0}/{1}/{2}", year, month, day );
            }
        }

        #endregion
    }
}

Software/PromoterSoftware/PromoterSoftware/Controllers/ProjectDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Helpers;
using Models;
using ViewModels;

namespace PromoterSoftware.Controllers
{
    public class ProjectDetailsController : Infrastructure.BaseController
    {
        private DatabaseContext db = new DatabaseContext();

        public ActionResult Index(Guid id)
        {
            var projectDetails = db.ProjectDetails.Include(p => p.Project)
                .Where(p => p.ProjectId == id && p.IsDeleted == false).Include(p => p.Store).Include(p => p.User)
                .OrderByDescending(p => p.CreationDate);

            var project = db.Projects.Where(c => c.Id == id).Select(c => c.Title);

            ViewBag.Title = "جزییات پروژه " + project.FirstOrDefault();
            return View(projectDetails.ToList());
        }

        public ActionResult Create(Guid id)
        {
            ViewBag.ProjectId = id;
            ViewBag.ProvinceId = new SelectList(db.Provinces.OrderBy(c => c.Title), "Id", "Title");
            ViewBag.StoreId = new SelectList(db.Stores, "Id", "Title");
            ViewBag.UserId = new SelectList(db.Users.Where(c => c.Role.Name == "supervisor" && c.IsDeleted == false && c.IsActive), "Id", "FullName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProjectDetail projectDetail, Guid id)
        {
            if (ModelState.IsValid)
            {
                projectDetail.ProjectId = id;
                projectDetail.IsDeleted = false;
                projectDetail.CreationDate = DateTime.Now;
                projectDetail.Id = Guid.NewGuid();
                db.ProjectDetails.Add(projectDetail);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = id });
            }

            ViewBag.ProjectId = id;
            ViewBag.StoreId = new SelectList(db.Stores, "Id", "Title", projectDetail.StoreId);
            ViewBag.UserId = new SelectList(db.Users.Where(c => c.Role.Name == "supervisor" && c.IsDeleted == false && c.IsActive), "Id", "FullName", projectDetail.UserId);
            return View(projectDetail);
        }

        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectDetail projectDetail = db.ProjectDetails.Find(id);
            if (projectDetail == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProjectId = projectDetail.ProjectId;
            ViewBag.StoreId = new SelectList(db.Stores, "Id", "Title", projectDetail.StoreId);
            ViewBag.UserId = new SelectList(db.Users.Where(c => c.Role.Name == "supervisor" && c.IsDeleted == false && c.IsActive), "Id", "FullName", projectDetail.UserId);
            return View(projectDetail);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProjectDetail projectDetail)
        {
            if (ModelState.IsValid)
            {
                projectDetail.IsDeleted = false;
                db.Entry(projectDetail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = projectDetail.ProjectId });
            }
            ViewBag.ProjectId = projectDetail.ProjectId;
            ViewBag.StoreId = new SelectList(db.Stores, "Id", "Title", projectDetail.StoreId);
            ViewBag.UserId = new SelectList(db.Users.Where(c => c.Role.Name == "supervisor" && c.IsDeleted == false && c.IsActive), "Id", "FullName", projectDetail.UserId);
            return View(projectDetail);
        }

        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectDetail projectDetail = db.ProjectDetails.Find(id);
            if (projectDetail == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProjectId = projectDetail.ProjectId;

            return View(projectDetail);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            ProjectDetail projectDetail = db.ProjectDetails.Find(id);
            projectDetail.IsDeleted = true;
            projectDetail.DeletionDate = DateTime.Now;

            db.SaveChanges();
            return RedirectToAction("Index", new { id = projectDetail.ProjectId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult FillCities(string id)
        {
            Guid provinceId = new Guid(id);
            var cities = db.Cities.Where(c => c.ProvinceId == provinceId).OrderBy(current => current.Title).ToList();
            List<DroupDownItemViewModel> cityItems = new List<DroupDownItemViewModel>();
            foreach (Models.City city in cities)
            {
                cityItems.Add(new DroupDownItemViewModel()
                {
                    Text = city.Title,
                    Value = city.Id.ToString()
                });
            }
            return Json(cityItems, JsonRequestBehavior.AllowGet);
        }

        public ActionResult FillStores(string id)
        {
            Guid cityId = new Guid(id);
            var stores = db.Stores.Where(c => c.CityId == cityId).OrderBy(current => current.Title).ToList();
            List<DroupDownItemViewModel> cityItems = new List<DroupDownItemViewModel>();
            foreach (Models.Store store in stores)
            {
                cityItems.Add(new DroupDownItemViewModel()
                {
                    Text = store.Title,
                    Value = store.Id.ToString()
                });
            }
            return Json(cityItems, JsonRequestBehavior.AllowGet);
        }


        #region SupervisorList

        public ActionResult SupervisorIndex(Guid id)
        {
            User user = GetUserInfo.GetUser();

            var projectDetails = db.ProjectDetails.Include(p => p.Project)
                .Where(p => p.ProjectId == id && p.UserId == user.Id && p.IsDeleted == false)
                .Include(p => p.Store).OrderByDescending(p => p.CreationDate);

            var project = db.Projects.Where(c => c.Id == id).Select(c => c.Title);

            ViewBag.Title = "جزییات پروژه " + project.FirstOrDefault();
            return View(projectDetails.ToList());
        }

        #endregion
    }
}

Software/PromoterSoftware/PromoterSoftware/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Helpers;
using Models;

namespace PromoterSoftware.Controllers
{
    public class ProjectsController : Infrastructure.BaseController
    {
        private DatabaseContext db = new DatabaseContext();

        public ActionResult Index()
        {
            var projects = db.Projects.Include(p => p.Customer).Where(p=>p.IsDeleted==false).OrderByDescending(p=>p.CreationDate);
            return View(projects.ToList());
        }

        public ActionResult Create()
        {
            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Title");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Project project, List<HttpPostedFileBase> attachments)
        {
            if (ModelState.IsValid)
            {

				project.IsDeleted=false;
				project.CreationDate= DateTime.Now; 
                project.Id = Guid.NewGuid();
                db.Projects.Add(project);

                #region Upload and resize image if needed

                if (attachments != null)
                {
                    foreach (HttpPostedFileBase t in attachments)
                    {
                        if (t != null)
                        {
                            string filename = Path.GetFileName(t.FileName);
                            string newFilename = Guid.NewGuid().ToString().Replace("-", string.Empty)
                                                 + Path.GetExtension(filename);

                            string newFilenameUrl = "/Uploads/ProjectAttachments/" + newFilename;
                            string physicalFilename = Server.MapPath(newFilenameUrl);

                            t.SaveAs(physicalFilename);

                            ProjectAttachment projectAttachment = new ProjectAttachment()
                            {
                                Id = Guid.NewGuid(),
                                FileUrl = newFilenameUrl,
                                CreationDate = DateTime.Now,
                                ProjectId = project.Id,
                                IsActive = true,
                                IsDeleted = false,
                            };
                            db.ProjectAttachments.Add(projectAttachment);
                        }
                    }
                }

                #endregion


                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Title", project.CustomerId);
            return View(project);
        }

       public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Title", project.CustomerId);
            return View(project);
        }
         
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Project project)
        {
            if (ModelState.IsValid)
            {
				project.IsDeleted=false;
                db.Entry(project).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Title", project.CustomerId);
            return View(project);
        }

        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Project project = db.Projects.Find(id);
			project.IsDeleted=true;
			project.DeletionDate=DateTime.Now;
 
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        #region Supervisor

        public ActionResult SupervisorIndex()
        {
            User user = GetUserInfo.GetUser();

            List<Project> projects=new List<Project>();

            if (user != null)
            {
                var projectDetails = db.ProjectDetails.Where(c => c.UserId == user.Id).Select(c => new
                {
                    c.ProjectId,
                    c.UserId
                });

                foreach (var projectDetail in projectDetails)
                {
                    if (projects.All(c => c.Id != projectDetail.ProjectId))
                    {
                        projects.Add(db.Projects.Find(projectDetail.ProjectId));
                    }
                }

            }

            return View(projects);
        }


        #endregion
    }
}

Software/PromoterSoftware/PromoterSoftware/Views/Projects/Create.cshtml
@model Models.Project

@{
		ViewBag.Title = "افزودن " + Server.HtmlDecode(Html.DisplayNameFor(model => model).ToString());
}
@section styles{
	@Html.Partial("BackEndLayout/_KendoResourcesPartial")
}
<div class="col-md-4">
	<div class="main-card mb-3 card">
		@ViewBag.description
	</div>
</div>

<div class="col-md-8">
	<div class="main-card mb-3 card">
		<div class="card-body">

			@using (Html.BeginForm("Create", "Projects", FormMethod.Post, new { enctype = "multipart/form-data" }))
			{
					@Html.AntiForgeryToken()



					<div class="position-relative form-group">
						@Html.LabelFor(model => model.Title)

						<input name="Title" id="Title" placeholder="@Html.DisplayNameFor(m=>m.Title)" type="text" class="form-control">
						@Html.ValidationMessageFor(model => model.Title)
					</div>
					<div class="position-relative form-group">
						@Html.LabelFor(model => model.StartDate)
						@Html.EditorFor(m => m.StartDate)
						@*<input name="StartDate" id="StartDate" placeholder= "@Html.DisplayNameFor(m=>m.StartDate)" type="text" class="form-control">*@
						@Html.ValidationMessageFor(model => model.StartDate)
					</div>
					<div class="position-relative form-group">
						@Html.LabelFor(model => model.EndDate)

						@Html.EditorFor(m => m.EndDate)
						@*<input name="EndDate" id="EndDate" placeholder= "@Html.DisplayNameFor(m=>m.EndDate)" type="text" class="form-control">*@
						@Html.ValidationMessageFor(model => model.EndDate)
					</div>
					<div class="position-relative form-group">
						@Html.LabelFor(model => model.CustomerId)

						@Html.DropDownList("CustomerId", null, String.Empty, new { @class = "form-control" })
						@Html.ValidationMessageFor(model => model.CustomerId)
					</div>


					<div class="position-relative form-group">
						<label>ضمیمه ها</label>
						@Html.Kendo().Upload().Name("attachments").Multiple(true).HtmlAttributes(new { @class = "form-control" })
					</div>

					<div class="position-relative form-group">
						@Html.LabelFor(model => model.Body)

						<textarea name="Body" id="Body" placeholder="@Html.DisplayNameFor(m=>m.Body)" class="form-control"></textarea>

						@Html.ValidationMessageFor(model => model.Body)
					</div>
					<div class="position-relative form-check">
						<label class="form-check-label">
							@Html.CheckBoxFor(model => model.IsActive)
							@Html.DisplayNameFor(m => m.IsActive)
						</label>

					</div>
											<div class="position-relative form-group">
												@Html.LabelFor(model => model.Description)

												<textarea name="Description" id="Description" placeholder="@Html.DisplayNameFor(m=>m.Description)" class="form-control"></textarea>

												@Html.ValidationMessageFor(model => model.Description)
											</div>



											<div class="button-box">
												<input type="submit" value="ایجاد" class="btn btn-primary" />
												@Html.ActionLink("بازگشت به فهرست", "Index")

											</div>

			}
		</div>
	</div>
</div>

Software/PromoterSoftware/PromoterSoftware/Views/Projects/Delete.cshtml
@model Models.Project

@{
    ViewBag.Title = "حذف " + Server.HtmlDecode(Html.DisplayNameFor(model => model).ToString());
}

<h2>@ViewBag.Title</h2>

<h3>آیا از حذف این مورد اطمینان دارید؟</h3>
<div>    
    <hr />
    <div class="form-horizontal">        
    
         <div class="form-group">
            @Html.LabelFor(model => model.Customer.Title, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Customer.Title)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Title)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.StartDate, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.StartDate)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.EndDate, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.EndDate)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.Body, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Body)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.IsActive, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.IsActive)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.CreationDate, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.CreationDate)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.LastModifiedDate, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.LastModifiedDate)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Description)
      </div></div>

  </div>  

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

       <div class="form-group" id="buttons">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="تایید حذف" class="btn btn-primary" />
				@Html.ActionLink("بازگشت به فهرست", "Index")
            </div>
        </div>
    }
</div>

Software/PromoterSoftware/PromoterSoftware/Views/Projects/Edit.cshtml
@model Models.Project

@{
    ViewBag.Title = "ویرایش " + Server.HtmlDecode(Html.DisplayNameFor(model => model).ToString());
}


<div class="col-md-4">
    <div class="main-card mb-3 card">
        @ViewBag.description
    </div>
</div>
                        
<div class="col-md-8">
<div class="main-card mb-3 card">
<div class="card-body">


@using (Html.BeginForm("Edit", "Projects",FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
        @Html.HiddenFor(model => model.Id)

         <div class="position-relative form-group">
            @Html.LabelFor(model => model.Title)
                                     <input name="Title" id="Title" placeholder= "@Html.DisplayNameFor(m=>m.Title)" type="text" class="form-control" value="@Model.Title">
                @Html.ValidationMessageFor(model => model.Title)
            </div>
       

         <div class="position-relative form-group">
            @Html.LabelFor(model => model.StartDate)
	         @Html.EditorFor(m => m.StartDate)
                @Html.ValidationMessageFor(model => model.StartDate)
            </div>
       

         <div class="position-relative form-group">
            @Html.LabelFor(model => model.EndDate)
	         @Html.EditorFor(m => m.EndDate)
                @Html.ValidationMessageFor(model => model.EndDate)
            </div>
       

         <div class="position-relative form-group">
            @Html.LabelFor(model => model.CustomerId)
                @Html.DropDownList("CustomerId",null, String.Empty,new{ @class= "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerId)
            </div>
	<div class="position-relative form-group">
		<label>ضمیمه ها</label>
		@Html.Kendo().Upload().Name("attachments").Multiple(true).HtmlAttributes(new { @class = "form-control" })
		
		<a href="/projectattachments/index/@Model.Id" class="mb-2 mr-2 btn btn-link" target="_blank" >مشاهده ضمیمه ها</a>
	</div>

         <div class="position-relative form-group">
            @Html.LabelFor(model => model.Body)
	         <textarea name="Body" id="Body" placeholder= "@Html.DisplayNameFor(m=>m.Body)" class="form-control"></textarea>
                @Html.ValidationMessageFor(model => model.Body)
            </div>
       

        	<div class="position-relative form-check">
			 <label class="form-check-label">
			     @Html.CheckBoxFor(model => model.IsActive)
			 @Html.DisplayNameFor(m => m.IsActive)
			 </label>    
                                             @Html.ValidationMessageFor(model => model.IsActive)
            </div>


						<div style="display: none;">@Html.EditorFor(model => model.CreationDate)</div>
         <div class="position-relative form-group">
            @Html.LabelFor(model => model.Description)
                                 <textarea name="Description" id="Description" placeholder= "@Html.DisplayNameFor(m=>m.Description)" class="form-control"></textarea>
                @Html.ValidationMessageFor(model => model.Description)
            </div>
       

   <div class="button-box">
                <input type="submit" value="ثبت" class="btn btn-primary" />
				@Html.ActionLink("بازگشت به فهرست", "Index")
           
        </div>
        
  
}
        </div>
        </div>
        </div>

Software/PromoterSoftware/PromoterSoftware/Views/Projects/Index.cshtml
@model IEnumerable<Models.Project>

@{
ViewBag.Title = "فهرست پروژه ها";
    
}
@section styles{
@Html.Partial("BackEndLayout/_KendoResourcesPartial")
}
<div class="col-md-12">
    <div class="main-card mb-3 card">
        <div class="card-body">

        @(Html.Kendo().Grid(Model)
              .Name("Grid")
              .Columns(columns =>
                  {
                              columns.Bound(model => model.Customer.Title);
        columns.Bound(model => model.Title);
        columns.Bound(model => model.StartDateStr);
        columns.Bound(model => model.EndDateStr);
        columns.Bound(model => model.IsActive);
        columns.Bound(model => model.CreationDateStr);
					columns.Bound(item => @item.Id).Title("دستورات").Filterable(false).Groupable(false)
							.Template(@<text>
									@Html.ActionLink("ویرایش", "Edit", new {id = @item.Id}, new {@class = "mb-2 mr-2 btn btn-primary" })
									@Html.ActionLink("حذف", "Delete", new {id = @item.Id}, new {@class = "mb-2 mr-2 btn btn-warning" })
									@Html.ActionLink("مدیریت جزییات", "index","ProjectDetails", new {id = @item.Id}, new {@class = "mb-2 mr-2 btn btn-info" })
									@Html.ActionLink("مدیریت محصولات", "index","ProjectProducts", new {id = @item.Id}, new {@class = "mb-2 mr-2 btn btn-success" })
									@Html.ActionLink("مدیریت ضمیمه ها", "index","ProjectAttachments", new {id = @item.Id}, new {@class = "mb-2 mr-2 btn btn-secondary" })
									</text>).Width(200);
									})
		.ToolBar(toolbar =>
		{
			toolbar.Custom().Action("Create","Projects").Text("افزودن");
		}
		)
		.DataSource(dataSource => dataSource
									.Server()

									.Model(model => model.Id(item => item.Id))
					)
	)

</div>
</div>
</div>

Software/PromoterSoftware/PromoterSoftware/Views/Projects/SupervisorIndex.cshtml
@model IEnumerable<Models.Project>

@{
ViewBag.Title = "فهرست پروژه ها";
    
}
@section styles{
@Html.Partial("BackEndLayout/_KendoResourcesPartial")
}
<div class="col-md-12">
    <div class="main-card mb-3 card">
        <div class="card-body">

        @(Html.Kendo().Grid(Model)
              .Name("Grid")
              .Columns(columns =>
                  {
                              columns.Bound(model => model.Customer.Title);
        columns.Bound(model => model.Title);
        columns.Bound(model => model.StartDateStr);
        columns.Bound(model => model.EndDateStr);
        columns.Bound(model => model.IsActive);
        columns.Bound(model => model.CreationDateStr);
					columns.Bound(item => @item.Id).Title("دستورات").Filterable(false).Groupable(false)
							.Template(@<text>
									@Html.ActionLink("مشاهده فروشگاه ها", "SupervisorIndex", "ProjectDetails", new {id = @item.Id}, new {@class = "mb-2 mr-2 btn btn-info" })
									@Html.ActionLink("مشاهده محصولات", "list","ProjectProducts", new {id = @item.Id}, new {@class = "mb-2 mr-2 btn btn-success" })
									@Html.ActionLink("مشاهده ضمیمه ها", "list", "ProjectAttachments", new {id = @item.Id}, new {@class = "mb-2 mr-2 btn btn-secondary" })
									</text>).Width(200);
									})
		.ToolBar(toolbar =>
		{
			toolbar.Custom().Action("Create","Projects").Text("افزودن");
		}
		)
		.DataSource(dataSource => dataSource
									.Server()

									.Model(model => model.Id(item => item.Id))
					)
	)

</div>
</div>
</div>