Software/PromoterSoftware/PromoterSoftware/Controllers/DailyPromoterPlansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Helpers;
using Models;
using ViewModels;

namespace PromoterSoftware.Controllers
{
    public class DailyPromoterPlansController : Infrastructure.BaseController
    {
        private DatabaseContext db = new DatabaseContext();

        public ActionResult Index(Guid id)
        {
            var dailyPromoterPlans = db.DailyPromoterPlans.Include(d => d.ProjectDetailPromoter).Where(d => d.ProjectDetailPromoterId == id && d.IsDeleted == false).OrderByDescending(d => d.ShiftDate);

            ProjectDetailPromoter projectDetailPromoter = db.ProjectDetailPromoters.Find(id);

            ViewBag.Title = "برنامه روزانه " + projectDetailPromoter.User.FullName + " در فروشگاه " +
                            projectDetailPromoter.ProjectDetail.Store.Title;

            return View(dailyPromoterPlans.ToList());
        }

        public ActionResult Create(Guid id)
        {
            ProjectDetailPromoter projectDetailPromoter = db.ProjectDetailPromoters.Find(id);

            ViewBag.Title = "افزودن به برنامه روزانه " + projectDetailPromoter.User.FullName + " در فروشگاه " +
                            projectDetailPromoter.ProjectDetail.Store.Title;


            ViewBag.ProjectDetailPromoterId = id;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DailyPromoterPlan dailyPromoterPlan, Guid id)
        {
            if (ModelState.IsValid)
            {
                dailyPromoterPlan.IsActive = true;
                dailyPromoterPlan.ProjectDetailPromoterId = id;
                dailyPromoterPlan.IsDeleted = false;
                dailyPromoterPlan.CreationDate = DateTime.Now;
                dailyPromoterPlan.Id = Guid.NewGuid();
                db.DailyPromoterPlans.Add(dailyPromoterPlan);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = id });
            }

            ViewBag.ProjectDetailPromoterId = id;
            return View(dailyPromoterPlan);
        }

        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DailyPromoterPlan dailyPromoterPlan = db.DailyPromoterPlans.Find(id);
            if (dailyPromoterPlan == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProjectDetailPromoterId = dailyPromoterPlan.ProjectDetailPromoterId;
            return View(dailyPromoterPlan);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(DailyPromoterPlan dailyPromoterPlan)
        {
            if (ModelState.IsValid)
            {
                if (dailyPromoterPlan.StartHour == 0 && dailyPromoterPlan.StartMin == 0)
                {
                    dailyPromoterPlan.StartHour = null;
                    dailyPromoterPlan.StartMin = null;
                }

                if (dailyPromoterPlan.FinishHour == 0 && dailyPromoterPlan.FinishMin == 0)
                {
                    dailyPromoterPlan.FinishHour = null;
                    dailyPromoterPlan.FinishMin = null;
                }
                dailyPromoterPlan.IsDeleted = false;
                db.Entry(dailyPromoterPlan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = dailyPromoterPlan.ProjectDetailPromoterId });
            }
            ViewBag.ProjectDetailPromoterId = dailyPromoterPlan.ProjectDetailPromoterId;
            return View(dailyPromoterPlan);
        }


        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DailyPromoterPlan dailyPromoterPlan = db.DailyPromoterPlans.Find(id);
            if (dailyPromoterPlan == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProjectDetailPromoterId = dailyPromoterPlan.ProjectDetailPromoterId;

            return View(dailyPromoterPlan);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            DailyPromoterPlan dailyPromoterPlan = db.DailyPromoterPlans.Find(id);
            dailyPromoterPlan.IsDeleted = true;
            dailyPromoterPlan.DeletionDate = DateTime.Now;

            db.SaveChanges();
            return RedirectToAction("Index", new { id = dailyPromoterPlan.ProjectDetailPromoterId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Promoter


        [Authorize(Roles = "promoter")]
        public ActionResult PromoterIndex()
        {
            User user = GetUserInfo.GetUser();

            var dailyPromoterPlans = db.DailyPromoterPlans.Include(d => d.ProjectDetailPromoter)
                .Where(d => d.ProjectDetailPromoter.UserId == user.Id && d.IsDeleted == false)
                .OrderByDescending(d => d.ShiftDate);


       

            ViewBag.Title = "برنامه روزانه ";

            return View(dailyPromoterPlans.ToList());
        }


        [Authorize(Roles = "promoter")]
        public ActionResult PromoterDailyPlanAction()
        {
            PromoterDailyPlanActionViewModel result = new PromoterDailyPlanActionViewModel() { IsStart = false };
            User user = GetUserInfo.GetUser();

            DailyPromoterPlan dailyPromoterPlan = db.DailyPromoterPlans.FirstOrDefault(c =>
                c.ProjectDetailPromoter.UserId == user.Id && c.ShiftDate == DateTime.Today);

            if (dailyPromoterPlan != null)
            {
                ViewBag.dailyPromoterPlanId = dailyPromoterPlan.Id;

                if (dailyPromoterPlan.StartHour != null)
                    result.IsStart = true;

                if (dailyPromoterPlan.FinishHour != null)
                    result.IsFinish = true;

                result.StartTime = dailyPromoterPlan.StartHourStr;
                result.FinishTime = dailyPromoterPlan.FinishHourStr;
                result.ShiftDate = dailyPromoterPlan.ShiftDateStr;

                Project project = dailyPromoterPlan.ProjectDetailPromoter.ProjectDetail.Project;
                result.ProjectTitle = project.Title;
                result.BrandTitle = project.Customer.Title;
                result.Description = project.Body;
                result.StoreTitle = dailyPromoterPlan.ProjectDetailPromoter.ProjectDetail.Store.Title;
                result.ProjectProducts = GetProjectProduct(project.Id, dailyPromoterPlan.Id);
                result.DailyPromoterPlanAttachments = db.DailyPromoterPlanAttachments.Where(c =>
                        c.DailyPromoterPlanId == dailyPromoterPlan.Id && c.IsDeleted == false && c.IsActive == true)
                    .ToList();

                result.SupervisorFullname = dailyPromoterPlan.ProjectDetailPromoter.User.FullName;
                result.ProjectAttachments = GetProjectAttachment(project.Id);
            }

            else
            {
                return RedirectToAction("NoPlan");
            }
            return View(result);
        }

        [Authorize(Roles = "promoter")]
        public ActionResult NoPlan()
        {
            return View();
        }
        [Authorize(Roles = "promoter")]
        public ActionResult PromoterDailyPlanActionById(Guid id)
        {
            PromoterDailyPlanActionViewModel result = new PromoterDailyPlanActionViewModel() { IsStart = false };
            User user = GetUserInfo.GetUser();

            DailyPromoterPlan dailyPromoterPlan = db.DailyPromoterPlans.Find(id);

            if (dailyPromoterPlan != null)
            {

                if (dailyPromoterPlan.ShiftDate == DateTime.Today)
                    return RedirectToAction("PromoterDailyPlanAction");

                ViewBag.dailyPromoterPlanId = dailyPromoterPlan.Id;

                if (dailyPromoterPlan.StartHour != null)
                    result.IsStart = true;

                if (dailyPromoterPlan.FinishHour != null)
                    result.IsFinish = true;

                result.StartTime = dailyPromoterPlan.StartHourStr;
                result.FinishTime = dailyPromoterPlan.FinishHourStr;
                result.ShiftDate = dailyPromoterPlan.ShiftDateStr;

                Project project = dailyPromoterPlan.ProjectDetailPromoter.ProjectDetail.Project;
                result.ProjectTitle = project.Title;
                result.BrandTitle = project.Customer.Title;
                result.Description = project.Body;
                result.StoreTitle = dailyPromoterPlan.ProjectDetailPromoter.ProjectDetail.Store.Title;
                result.ProjectProducts = GetProjectProduct(project.Id, dailyPromoterPlan.Id);
                result.DailyPromoterPlanAttachments = db.DailyPromoterPlanAttachments.Where(c =>
                        c.DailyPromoterPlanId == dailyPromoterPlan.Id && c.IsDeleted == false && c.IsActive == true)
                    .ToList();

                result.SupervisorFullname = dailyPromoterPlan.ProjectDetailPromoter.User.FullName;
                result.ProjectAttachments = GetProjectAttachment(project.Id);
            }

            return View(result);
        }

        public List<ProjectProductItem> GetProjectProduct(Guid projectId, Guid dailyPromoterPlanId)
        {
            List<ProjectProductItem> result = new List<ProjectProductItem>();

            var projectProducts = db.ProjectProducts

Software/PromoterSoftware/PromoterSoftware/Controllers/ProjectDetailPromotersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Helpers;
using Models;
using ViewModels;

namespace PromoterSoftware.Controllers
{
    public class ProjectDetailPromotersController : Infrastructure.BaseController
    {
        private DatabaseContext db = new DatabaseContext();

        public ActionResult Index(Guid id)
        {
            ProjectDetailPromoterViewModel result = new ProjectDetailPromoterViewModel();
            List<ProjectDetailPromoter> projectDetailPromoters = db.ProjectDetailPromoters
                .Where(p => p.ProjectDetailId == id && p.IsDeleted == false).OrderByDescending(p => p.CreationDate)
                .ToList();


            var projectDetail = db.ProjectDetails.Find(id);

            if (projectDetail != null)
            {
                ViewBag.UserId = new SelectList(db.Users.Where(c => c.Role.Name == "promoter" && c.CityId == projectDetail.Store.CityId), "Id",
                    "FullName");

                ViewBag.Title = "فهرست پروموترهای پروژه " + projectDetail.Project.Title + " فروشگاه " +
                                projectDetail.Store.Title;

                result.ProjectDetailPromoters = projectDetailPromoters;
                result.StartDate = projectDetail.Project.StartDateStr;
                result.EndDate = projectDetail.Project.EndDateStr;
                result.SalaryPerHour = projectDetail.SalaryPerHourStr;
                result.TransportationAmount = projectDetail.TransportationAmountStr;
                result.StartHour = projectDetail.StartHourStr;
                result.FinishHour = projectDetail.FinishHourStr;
                result.ProjectDetailId = id;
            }

            return View(result);
        }

        [HttpPost, ActionName("Index")]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePromoter(ProjectDetailPromoterViewModel input)
        {
            if (db.ProjectDetailPromoters.Any(c =>
                c.UserId == input.UserId && c.ProjectDetailId == input.ProjectDetailId && c.IsDeleted == false))
            {
                TempData["invalidPromoter"] = "پروموتر انتخابی قبلا برای این پروژه انتخاب شده است. پروموتر دیگری را انتخاب کنید.";
                return RedirectToAction("index", new { id = input.ProjectDetailId });

            }

            ProjectDetailPromoter projectDetailPromoter = new ProjectDetailPromoter()
            {
                Id = Guid.NewGuid(),
                IsActive = true,
                IsDeleted = false,
                IsFullTime = true,
                ProjectDetailId = input.ProjectDetailId,
                UserId = input.UserId.Value,
                CreationDate = DateTime.Now,
            };
            db.ProjectDetailPromoters.Add(projectDetailPromoter);

            var projectDetail = db.ProjectDetails.Find(input.ProjectDetailId);

            string totalTimeSpan = (projectDetail.Project.EndDate.Value - projectDetail.Project.StartDate).ToString();

            int totalDays = Convert.ToInt32(totalTimeSpan.Split('.')[0]);
            for (int i = 0; i <= totalDays; i++)
            {
                DailyPromoterPlan dailyPromoterPlan = new DailyPromoterPlan()
                {
                    Id = Guid.NewGuid(),
                    ProjectDetailPromoterId = projectDetailPromoter.Id,
                    ShiftDate = projectDetail.Project.StartDate.AddDays(i),
                    CreationDate = DateTime.Now,
                    IsDeleted = false,
                    IsActive = true,

                };

                db.DailyPromoterPlans.Add(dailyPromoterPlan);
            }

            db.SaveChanges();
            return RedirectToAction("index", new { id = input.ProjectDetailId });
        }

        public ActionResult Create()
        {
            ViewBag.ProjectDetailId = new SelectList(db.ProjectDetails, "Id", "Description");
            ViewBag.UserId = new SelectList(db.Users, "Id", "FullName");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProjectDetailPromoter projectDetailPromoter)
        {
            if (ModelState.IsValid)
            {
                projectDetailPromoter.IsDeleted = false;
                projectDetailPromoter.CreationDate = DateTime.Now;
                projectDetailPromoter.Id = Guid.NewGuid();
                db.ProjectDetailPromoters.Add(projectDetailPromoter);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProjectDetailId = new SelectList(db.ProjectDetails, "Id", "Description", projectDetailPromoter.ProjectDetailId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "FullName", projectDetailPromoter.UserId);
            return View(projectDetailPromoter);
        }

        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectDetailPromoter projectDetailPromoter = db.ProjectDetailPromoters.Find(id);
            if (projectDetailPromoter == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProjectDetailId = new SelectList(db.ProjectDetails, "Id", "Description", projectDetailPromoter.ProjectDetailId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "FullName", projectDetailPromoter.UserId);
            return View(projectDetailPromoter);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProjectDetailPromoter projectDetailPromoter)
        {
            if (ModelState.IsValid)
            {
                projectDetailPromoter.IsDeleted = false;
                db.Entry(projectDetailPromoter).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProjectDetailId = new SelectList(db.ProjectDetails, "Id", "Description", projectDetailPromoter.ProjectDetailId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "FullName", projectDetailPromoter.UserId);
            return View(projectDetailPromoter);
        }

        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectDetailPromoter projectDetailPromoter = db.ProjectDetailPromoters.Find(id);
            if (projectDetailPromoter == null)
            {
                return HttpNotFound();
            }
            return View(projectDetailPromoter);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            ProjectDetailPromoter projectDetailPromoter = db.ProjectDetailPromoters.Find(id);
            projectDetailPromoter.IsDeleted = true;
            projectDetailPromoter.DeletionDate = DateTime.Now;

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


      
    }
}

Software/PromoterSoftware/PromoterSoftware/Views/ProjectDetailPromoters/Create.cshtml
@model Models.ProjectDetailPromoter

@{
    ViewBag.Title = "افزودن " + Server.HtmlDecode(Html.DisplayNameFor(model => model).ToString());
}

<div class="col-md-4">
    <div class="main-card mb-3 card">
        @ViewBag.description
    </div>
</div>
                        
<div class="col-md-8">
<div class="main-card mb-3 card">
<div class="card-body">

@using (Html.BeginForm("Create", "ProjectDetailPromoters",FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    

    <div class="position-relative form-group">
            @Html.LabelFor(model => model.UserId)
            
                @Html.DropDownList("UserId",null, String.Empty,new{ @class= "form-control" })
                @Html.ValidationMessageFor(model => model.UserId)
        </div>
    <div class="position-relative form-group">
            @Html.LabelFor(model => model.ProjectDetailId)
            
                @Html.DropDownList("ProjectDetailId",null, String.Empty,new{ @class= "form-control" })
                @Html.ValidationMessageFor(model => model.ProjectDetailId)
        </div>
			<div class="position-relative form-check">
			 <label class="form-check-label">
			     @Html.CheckBoxFor(model => model.IsFullTime)
			 @Html.DisplayNameFor(m => m.IsFullTime)
			 </label>
            
                       </div>
			<div class="position-relative form-check">
			 <label class="form-check-label">
			     @Html.CheckBoxFor(model => model.IsActive)
			 @Html.DisplayNameFor(m => m.IsActive)
			 </label>
            
                       </div>
    <div class="position-relative form-group">
            @Html.LabelFor(model => model.Description)
            
                   <textarea name="Description" id="Description" placeholder= "@Html.DisplayNameFor(m=>m.Description)" class="form-control"></textarea>

                @Html.ValidationMessageFor(model => model.Description)
        </div>



       <div class="button-box">
                <input type="submit" value="ایجاد" class="btn btn-primary" />
				@Html.ActionLink("بازگشت به فهرست", "Index")
           
        </div>
   
}
        </div>
        </div>
        </div>

Software/PromoterSoftware/PromoterSoftware/Views/ProjectDetailPromoters/Delete.cshtml
@model Models.ProjectDetailPromoter

@{
    ViewBag.Title = "حذف " + Server.HtmlDecode(Html.DisplayNameFor(model => model).ToString());
}

<h2>@ViewBag.Title</h2>

<h3>آیا از حذف این مورد اطمینان دارید؟</h3>
<div>    
    <hr />
    <div class="form-horizontal">        
    
         <div class="form-group">
            @Html.LabelFor(model => model.ProjectDetail.Description, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.ProjectDetail.Description)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.User.FullName, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.User.FullName)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.IsFullTime, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.IsFullTime)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.IsActive, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.IsActive)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.CreationDate, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.CreationDate)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.LastModifiedDate, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.LastModifiedDate)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Description)
      </div></div>

  </div>  

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

       <div class="form-group" id="buttons">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="تایید حذف" class="btn btn-primary" />
				@Html.ActionLink("بازگشت به فهرست", "Index")
            </div>
        </div>
    }
</div>

Software/PromoterSoftware/PromoterSoftware/Views/ProjectDetailPromoters/Edit.cshtml
@model Models.ProjectDetailPromoter

@{
    ViewBag.Title = "ویرایش " + Server.HtmlDecode(Html.DisplayNameFor(model => model).ToString());
}


<div class="col-md-4">
    <div class="main-card mb-3 card">
        @ViewBag.description
    </div>
</div>
                        
<div class="col-md-8">
<div class="main-card mb-3 card">
<div class="card-body">


@using (Html.BeginForm("Edit", "ProjectDetailPromoters",FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
        @Html.HiddenFor(model => model.Id)

         <div class="position-relative form-group">
            @Html.LabelFor(model => model.UserId)
                @Html.DropDownList("UserId",null, String.Empty,new{ @class= "form-control" })
                @Html.ValidationMessageFor(model => model.UserId)
            </div>
       

         <div class="position-relative form-group">
            @Html.LabelFor(model => model.ProjectDetailId)
                @Html.DropDownList("ProjectDetailId",null, String.Empty,new{ @class= "form-control" })
                @Html.ValidationMessageFor(model => model.ProjectDetailId)
            </div>
       

        	<div class="position-relative form-check">
			 <label class="form-check-label">
			     @Html.CheckBoxFor(model => model.IsFullTime)
			 @Html.DisplayNameFor(m => m.IsFullTime)
			 </label>    
                                             @Html.ValidationMessageFor(model => model.IsFullTime)
            </div>
       

        	<div class="position-relative form-check">
			 <label class="form-check-label">
			     @Html.CheckBoxFor(model => model.IsActive)
			 @Html.DisplayNameFor(m => m.IsActive)
			 </label>    
                                             @Html.ValidationMessageFor(model => model.IsActive)
            </div>
       

	 @Html.HiddenFor(model => model.CreationDate)
         <div class="position-relative form-group">
            @Html.LabelFor(model => model.Description)
                                 <textarea name="Description" id="Description" placeholder= "@Html.DisplayNameFor(m=>m.Description)" class="form-control"></textarea>
                @Html.ValidationMessageFor(model => model.Description)
            </div>
       

   <div class="button-box">
                <input type="submit" value="ثبت" class="btn btn-primary" />
				@Html.ActionLink("بازگشت به فهرست", "Index")
           
        </div>
        
  
}
        </div>
        </div>
        </div>

Software/PromoterSoftware/PromoterSoftware/Views/ProjectDetailPromoters/Index.cshtml
@model ViewModels.ProjectDetailPromoterViewModel
@section styles{
@Html.Partial("BackEndLayout/_KendoResourcesPartial")

	<style>
		.card-add {
			margin-bottom: 15px;
			background-color: #f8f9fa;
		}
		.card-add-heading {
			border-bottom: 1px solid #3f6ad8;
			padding: 15px;
			font-size: 1.3rem;
			color: #3f6ad8
		}.card-add-body  {
			 padding: 15px;

		}.card-add-body .row {
			direction: rtl;
		}

		 .dirright {
			 direction: rtl;
		 }


	</style>
}
<div class="col-md-12">
    <div class="main-card mb-3 card">
        <div class="card-body">
	        <div class="row dirright">
		        <div class="col-md-8">
			        <div class="card-add">
				        <div class="card-add-heading">افزودن پروموتر</div>
				        <div class="card-add-body">
					        @if (TempData["invalidPromoter"] != null)
					        {
						        <p class="alert alert-danger" id="wrongEmail">@TempData["invalidPromoter"]</p>
					        }
					        @using (Html.BeginForm())
					        {
						        @Html.AntiForgeryToken()
						        @Html.HiddenFor(m => m.ProjectDetailId)
						        <div class="row">
							        <div class="col-md-4">پروموتر</div>
							        <div class="col-md-8">
								        @Html.DropDownList("UserId", null, String.Empty, new {@class = "form-control", @required = "required"})
							        </div>
						        </div>
						        <div class="row">
							        <div class="col-md-4"></div>
							        <div class="col-md-8 pt-2">
								        <input type="submit" value="ثبت" class="btn btn-primary"/>
							        </div>
						        </div>
					        }

				        </div>
			        </div>
		        </div>
		        <div class="col-md-4">
			        <table class="table table-bordered">
				        <tr>
					        <td>تاریخ شروع پروژه</td>
					        <td>
						        @Model.StartDate
					        </td>
				        </tr>
				        <tr>
					        <td>تاریخ پایان پروژه</td>
					        <td>@Model.EndDate</td>
				        </tr>
				        <tr>
					        <td>ساعت کاری</td>
					        <td>@Model.StartHour لغایت @Model.FinishHour</td>
				        </tr>
				        <tr>
					        <td>دستمزد ساعتی</td>
					        <td>@Model.SalaryPerHour</td>
				        </tr>
				        <tr>
					        <td>هزینه ایاب ذهاب</td>
					        <td>@Model.TransportationAmount</td>
				        </tr>
			        </table>
		        </div>
	        </div>
	     

	        @(Html.Kendo().Grid(Model.ProjectDetailPromoters)
              .Name("Grid")
              .Columns(columns =>
                  {
        columns.Bound(model => model.User.FullName).Title("پروموتر");
        columns.Bound(model => model.IsFullTime);
        columns.Bound(model => model.IsActive);
					columns.Bound(item => @item.Id).Title("دستورات").Filterable(false).Groupable(false)
							.Template(@<text>
									@Html.ActionLink("مشاهده برنامه روزانه", "index","DailyPromoterPlans", new {id = @item.Id}, new {@class = "k-button"})
									@Html.ActionLink("حذف", "Delete", new {id = @item.Id}, new {@class = "k-button"})
									</text>).Width(200);  
		})
	         
		.DataSource(dataSource => dataSource
									.Server()
							
									.Model(model => model.Id(item => item.Id))
					)              
	)

</div>
</div>
</div>